BASE_URL = "https://stellarburgers.education-services.ru/api"
REGISTER_ENDPOINT = "/auth/register"
LOGIN_ENDPOINT = "/auth/login"
DELETE_USER_ENDPOINT = "/auth/user"
INGREDIENTS_ENDPOINT = "/ingredients"
ORDERS_ENDPOINT = "/orders"